apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: lustre.csi.klustrefs.io
spec:
  attachRequired: false
  fsGroupPolicy: ReadWriteOnceWithFSType
  podInfoOnMount: true
  volumeLifecycleModes:
  - Persistent
