apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccount-klustre-csi-node.yaml
  - clusterrole-klustre-csi-node.yaml
  - configmap-klustre-csi-settings.yaml
  - csidriver-lustre.csi.klustrefs.io.yaml
  - daemonset-klustre-csi-node.yaml
  - storageclass-klustre-static.yaml

images:
  - name: ghcr.io/klustrefs/klustre-csi-plugin
    newTag: v0.1.2
